// /shared/gazetteer.js
const ALIAS = {
  UK: "GBR",
  Britain: "GBR",
  "United Kingdom": "GBR",
  Russia: "RUS",
  "United States": "USA",
  US: "USA",
  USA: "USA",
  Iran: "IRN",
  Syria: "SYR",
  NorthKorea: "PRK",
  SouthKorea: "KOR",
  Czechia: "CZE",
  "Czech Republic": "CZE",
  "Democratic Republic of the Congo": "COD",
  Congo: "COG",
  Vietnam: "VNM",
  Laos: "LAO",
  France: "FRA",
  Germany: "DEU",
  Spain: "ESP",
  Italy: "ITA",
  Poland: "POL",
  Austria: "AUT",
  Netherlands: "NLD",
  Belgium: "BEL",
  Switzerland: "CHE",
  Portugal: "PRT",
  Denmark: "DNK",
  Sweden: "SWE",
  Norway: "NOR",
  Finland: "FIN",
  Greece: "GRC",
  Turkey: "TUR",
  Egypt: "EGY",
  China: "CHN",
  Japan: "JPN",
  India: "IND",
  Brazil: "BRA",
  Argentina: "ARG",
  Mexico: "MEX",
  Canada: "CAN",
  Australia: "AUS"
};

const asISO = (s) => ALIAS[s] || s;

module.exports = { asISO, ALIAS };